"""Add bookings table with exclusion constraint

Revision ID: 2c9390f1b042
Revises: fddf05d1b636
Create Date: 2026-08-06 05:34:58.270032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c9390f1b042'
down_revision = 'fddf05d1b636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Manually added: btree_gist is required for the exclusion
    # constraint below to work at all. GiST indexes natively support
    # range-overlap operators (&&) but NOT equality (=) on a plain
    # UUID column -- btree_gist adds that support, which is what lets
    # us combine "same resource_id" (equality) with "overlapping time
    # range" (&&) in a single exclusion constraint. Must run BEFORE
    # create_table, since the constraint below depends on it.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_table('bookings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('resource_id'), '='), (sa.text('tstzrange(start_time, end_time)'), '&&'), where=sa.text("status = 'confirmed'"), using='gist', name='ex_bookings_no_overlap'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_resource_id'), ['resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_resource_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_id'))

    op.drop_table('bookings')
    # Note: intentionally NOT dropping the btree_gist extension here.
    # It's harmless to leave installed, and dropping it could break
    # other objects if anything else ever comes to depend on it --
    # extensions are cheap to leave, risky to drop reflexively.
    # ### end Alembic commands ###
