"""Add timezone to organizations

Revision ID: 50171e3f9db4
Revises: 2c9390f1b042
Create Date: 2026-08-08 23:03:16.903808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50171e3f9db4'
down_revision = '2c9390f1b042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
