"""Add organization_invites table

Revision ID: b447817e048a
Revises: 50171e3f9db4
Create Date: 2026-08-10 11:00:34.895835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b447817e048a'
down_revision = '50171e3f9db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invites',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_invites_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_invites_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('uq_pending_invite_per_org_email', ['organization_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_invites', schema=None) as batch_op:
        batch_op.drop_index('uq_pending_invite_per_org_email', postgresql_where=sa.text("status = 'pending'"))
        batch_op.drop_index(batch_op.f('ix_organization_invites_token_hash'))
        batch_op.drop_index(batch_op.f('ix_organization_invites_organization_id'))

    op.drop_table('organization_invites')
    # ### end Alembic commands ###
